hud_django_v1.0/template_django/DjangoHUD/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('DjangoHUDApp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'DjangoHUDApp.views.handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hud_django_v1.0/template_django/DjangoHUDApp/urls.py
from django.urls import path
from . import views

app_name = 'DjangoHUDApp'
urlpatterns = [
    # in use
    
    #general pages
    path('', views.pageLogin, name='pageLogin'),
    path('index', views.index, name='index'),
    path('404/', views.error404, name='error404'),
    path('page/error', views.pageError, name='pageError'),  
    path('logout/', views.logout_view, name='logout'),

    #product pages
    path('product', views.pageProduct, name='pageProduct'),
    path('add-product', views.add_product, name='add_product'),
    path('product-details/<int:product_id>/', views.product_details, name='pageProductDetails'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),

    #order pages
    path('add-shipment', views.add_shipment, name='add_shipment'),
    path('order', views.pageOrder, name='pageOrder'),
    path('order-details/<int:shipment_id>/', views.pageOrderDetails, name='pageOrderDetails'),
    path('order-details/<int:shipment_id>/print/', views.order_print, name='order_print'),
    path('delete-shipment/<int:shipment_id>/', views.delete_shipment, name='delete_shipment'),
    
    #warehouse pages
    path('warehouse', views.pageWarehouse, name='pageWarehouse'),
    path('stock-per-warehouse/<str:warehouse_name>/', views.stockPerWarehouse, name='pageStockPerWarehouse'),

    #stock pages
    path('page/data-management', views.pageDataManagement, name='pageDataManagement'),

    #recipient pages
    path('recipient', views.pageRecipient, name='pageRecipient'),

    # not in use
    path('analytics/', views.analytics, name='  '),
    path('chart/js/', views.chartJs, name='chartJs'),
    path('chart/apex/', views.chartApex, name='chartApex'),
]

handler404 = 'DjangoHUDApp.views.handler404'

hud_django_v1.0/template_django/DjangoHUDApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm
from django.http import HttpResponse  # Add this import
from .forms import ProductForm, ShipmentForm, ShipmentItemFormSet
from .models import Product, Shipment, Warehouse, Recipient, ShipmentItem, Stock, ProductCategory, ProductUsage  
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Sum,F, Q
from django.contrib.auth.decorators import login_required
from .filters import ProductFilter, ShipmentFilter, RecipientFilter, StockFilter
from django.utils.dateparse import parse_date
from django.utils import timezone
from django.contrib import messages
import pandas as pd
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from django.core.exceptions import ValidationError
from .models import ProductCategory, ProductUsage
from django.urls import reverse
from django.db.models import Q
from datetime import timedelta
from django.db.models import Sum, Max


# Function for loging a user 
def pageLogin(request):
    if request.method == 'GET':
        form = LoginForm()
    else:  # POST request
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('DjangoHUDApp:index')  # Make sure 'dashboard' is a valid named route in your urls.py
            else:
                # For debugging: Return a simple response indicating failure
                return HttpResponse("Invalid login attempt", status=401)
        else:
            # For debugging: Indicate form is not valid
            return HttpResponse("Form is not valid", status=400)
    
    context = {
        "form": form,
        "appSidebarHide": 1,
        "appHeaderHide": 1,
        "appContentClass": 'p-0'
    }
    return render(request, "pages/login.html", context)

def logout_view(request):
     logout(request)
     return redirect('DjangoHUDApp:pageLogin')

# Function for creating a product 
@login_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            product.owners.set(request.user.groups.all())  # Assign the product to the user's groups
            product.save()
            return redirect('DjangoHUDApp:pageProduct')  # Redirect to an appropriate page after saving
        else:
            return render(request, 'pages/add_product.html', {
                'form': form,
                'product_category_choices': Product.PRODUCT_CATEGORY,
                'product_usage_choices': Product.PRODUCT_USAGE,
                'unit_of_measurement_choices': Product.MEASUREMENT_TYPES,
            })
    else:
        form = ProductForm()
        context = {
            'form': form,
            'product_category_choices': ProductCategory.objects.all(),
            'product_usage_choices': ProductUsage.objects.all(),
            'unit_of_measurement_choices': Product.MEASUREMENT_TYPES,
        }
        return render(request, 'pages/add_product.html', context)
    
    
@login_required
def pageProduct(request):
    user_groups = request.user.groups.all()
    if request.user.is_superuser:
        products_list = Product.objects.all()
    else:
        products_list = Product.objects.filter(owners__in=user_groups).distinct()

    product_filter = ProductFilter(request.GET, queryset=products_list)
    products_list = product_filter.qs

    paginator = Paginator(products_list, 10)  # Show 10 products per page
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {'products': products, 'filter': product_filter}
    return render(request, "pages/all-products.html", context)



@login_required
def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product.delete()
    messages.success(request, 'Shipment deleted successfully.')
    return redirect(reverse('DjangoHUDApp:pageProduct'))


# Function for individual product details
@login_required
def product_details(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('DjangoHUDApp:pageProduct')  # Redirect to an appropriate page after updating
    else:
        form = ProductForm(instance=product)
    
    context = {
        'form': form,
        'product': product,
        'product_category_choices': Product.category,
        'product_usage_choices': Product.usage,
        'unit_of_measurement_choices': Product.MEASUREMENT_TYPES,
    }
    return render(request, 'pages/product-details.html', context)


@login_required
def add_shipment(request):
    if request.method == 'POST':
        form = ShipmentForm(request.POST, request.FILES)
        formset = ShipmentItemFormSet(request.POST, prefix='shipmentitem', user=request.user)

        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    shipment = form.save(commit=False)
                    shipment.user = request.user
                    shipment.date = timezone.now()
                    shipment.save()

                    formset.instance = shipment
                    formset.save()

                    return redirect('DjangoHUDApp:pageOrder')
            except ValidationError as e:
                form.add_error(None, e)
        else:
            print(form.errors)
            print(formset.errors)
    else:
        form = ShipmentForm()
        formset = ShipmentItemFormSet(prefix='shipmentitem', user=request.user)

    return render(request, 'pages/add_order.html', {'form': form, 'formset': formset})


@login_required
def delete_shipment(request, shipment_id):
    shipment = get_object_or_404(Shipment, id=shipment_id)
    shipment.delete()
    messages.success(request, 'Shipment deleted successfully.')
    return redirect(reverse('DjangoHUDApp:pageOrder'))

@login_required
def pageOrder(request):
    user = request.user

    # Admin users see all shipments
    if user.is_superuser:
        shipments_list = Shipment.objects.all()
    else:
        # Filter shipments by the groups of the user
        user_groups = user.groups.values_list('name', flat=True)
        if 'ΔΙΔΕΣ' in user_groups:
            # Users in ΔΙΔΕΣ see shipments from all users in this group
            shipments_list = Shipment.objects.filter(user__groups__name='ΔΙΔΕΣ')
        elif 'ΔΟΡΥΦΟΡΙΚΑ' in user_groups:
            # Users in ΔΟΡΥΦΟΡΙΚΑ only see their own shipments
            shipments_list = Shipment.objects.filter(user=user)
        else:
            # Default to no shipments if no specific group is found
            shipments_list = Shipment.objects.none()

    # Apply the filter
    shipments_filter = ShipmentFilter(request.GET, queryset=shipments_list)
    shipments_list = shipments_filter.qs

    # Sort by most recent date
    shipments_list = shipments_list.order_by('-date')

    # Paginate the results
    paginator = Paginator(shipments_list, 10)  # Show 10 shipments per page
    page_number = request.GET.get('page')
    shipments = paginator.get_page(page_number)

    context = {
        'shipments': shipments,
        'filter': shipments_filter,
    }
    return render(request, "pages/all-orders.html", context)

    
@login_required
def pageWarehouse(request):
    user_groups = request.user.groups.values_list('name', flat=True)

    if request.user.is_superuser or 'Admin' in user_groups:
        warehouses_list = Warehouse.objects.annotate(
            total_stock=Sum('stocks__quantity'),
            last_shipment_date=Max('shipmentitem__shipment__date')
        )
    elif 'ΔΟΡΥΦΟΡΙΚΑ' in user_groups:
        warehouses_list = Warehouse.objects.filter(name="ΔΟΡΥΦΟΡΙΚΑ").annotate(
            total_stock=Sum('stocks__quantity'),
            last_shipment_date=Max('shipmentitem__shipment__date')
        )
    elif 'ΔΙΔΕΣ' in user_groups:
        warehouses_list = Warehouse.objects.filter(name__in=["ΚΕΠΙΚ", "ΤΑΓΜΑ"]).annotate(
            total_stock=Sum('stocks__quantity'),
            last_shipment_date=Max('shipmentitem__shipment__date')
        )
    else:
        warehouses_list = Warehouse.objects.none()

    context = {'warehouses': warehouses_list}
    return render(request, "pages/warehouses.html", context)

@login_required
def pageDataManagement(request):
    if request.method == 'POST' and request.FILES.get('file'):
        file = request.FILES['file']
        file_name = file.name

        if file_name.endswith('.csv'):
            df = pd.read_csv(file)
        elif file_name.endswith('.xlsx'):
            df = pd.read_excel(file, header=0)
        else:
            return HttpResponse("Unsupported file format", status=400)

        # Strip whitespace from column names to avoid KeyError
        df.columns = df.columns.str.strip()

        # Print columns for debugging after stripping
        print("DataFrame columns after stripping:", df.columns)

        # Fill NaN values with empty strings to avoid errors
        df.fillna('', inplace=True)

        # Check for required columns and print a warning if any are missing
        required_columns = ['Προιόν', 'Κατηγορία', 'Χρήση', 'Μερίδα', 'Απ. ΤΑΓΜΑ', 'Απ. ΚΕΠΙΚ', 'Απ. ΔΟΡΥΦΟΡΙΚΑ']
        missing_columns = [col for col in required_columns if col not in df.columns]

hud_django_v1.0/template_django/DjangoHUDApp/templates/pages/all-products.html
{% extends 'base.html' %}
{% load static %}
{% load filters_tags %}

{% block title %}Products{% endblock %}

{% block css %}
    <link href="{% static 'css/lightbox.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static 'js/lightbox.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="d-flex align-items-center mb-3">
        <div>
            <h1 class="page-header mb-0">Λίστα Προιόντων</h1>
        </div>
        
        <div class="ms-auto">
            <a href="add-product" class="btn btn-outline-theme"><i class="fa fa-plus-circle fa-fw me-1"></i> Νέο Προιόν</a>
        </div>
    </div>
    <!-- Include the filter form -->
    {% render_product_filter_form filter %}
    <div class="card">
        {% comment %} <ul class="nav nav-tabs nav-tabs-v2 px-4">
            <li class="nav-item me-3"><a href="#allTab" class="nav-link active px-2" data-bs-toggle="tab">All</a></li>
            <li class="nav-item me-3"><a href="#publishedTab" class="nav-link px-2" data-bs-toggle="tab">Published</a></li>
            <li class="nav-item me-3"><a href="#expiredTab" class="nav-link px-2" data-bs-toggle="tab">Expired</a></li>
            <li class="nav-item me-3"><a href="#deletedTab" class="nav-link px-2" data-bs-toggle="tab">Deleted</a></li>
        </ul> {% endcomment %}
        <div class="tab-content p-4">
            <div class="tab-pane fade show active" id="allTab">

                <!-- BEGIN table -->
                <div class="table-responsive">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th class="pt-0 pb-2">Προιόν</th>
                                <th class="pt-0 pb-2">Απόθεμα</th>
                                <th class="pt-0 pb-2">Κατηγορία</th>
                                <th class="pt-0 pb-2">Χρήση</th>
                                <th class="border-top-0 pt-0 pb-2">Διαγραφή</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <div class="w-50px h-50px bg-inverse bg-opacity-25 d-flex align-items-center justify-content-center">
                                                {% if product.image %}
                                                    <a href="{{ product.image.url }}" data-lightbox="product-{{ product.id }}" data-title="{{ product.name }}">
                                                        <img alt="{{ product.name }}" class="mw-100 mh-100" src="{{ product.image.url }}">
                                                    </a>
                                                {% else %}
                                                    <img alt="" class="mw-100 mh-100" src="{% static 'img/default-image.jpg' %}">
                                                {% endif %}
                                            </div>
                                            <div class="ms-3">
                                                <a href="{% url 'DjangoHUDApp:pageProductDetails' product.id %}" class="text-inverse text-opacity-75 text-decoration-none">{{ product.name }}</a>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="align-middle">{{ product.stock }}</td> <!-- Assuming you have a stock field -->
                                    <td class="align-middle">{{ product.category }}</td>
                                    <td class="align-middle">{{ product.usage }}</td>
                                    <td class="align-middle">
                                        <form method="post" action="{% url 'DjangoHUDApp:delete_product' product.id %}" style="display:inline;">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5" class="text-center">No products found.</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- END table -->
                
                <div class="d-md-flex align-items-center">
                    <div class="me-md-auto text-md-left text-center mb-2 mb-md-0">
                        Showing {{ products.start_index }} to {{ products.end_index }} of {{ products.paginator.count }} entries
                    </div>
                    <ul class="pagination mb-0 justify-content-center">
                        {% if products.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page=1">Πρώτη</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Προηγούμενη</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link">Πρώτη Σελίδα</a></li>
                            <li class="page-item disabled"><a class="page-link">Προηγούμενη</a></li>
                        {% endif %}
                        
                        {% for num in products.paginator.page_range %}
                            {% if products.number == num %}
                                <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
                                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if products.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Επόμενη</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ products.paginator.num_pages }}">Τελευταία</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link">Επόμενη</a></li>
                            <li class="page-item disabled"><a class="page-link">Τελευταία</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="card-arrow">
            <div class="card-arrow-top-left"></div>
            <div class="card-arrow-top-right"></div>
            <div class="card-arrow-bottom-left"></div>
            <div class="card-arrow-bottom-right"></div>
        </div>
    </div>
{% endblock %}

hud_django_v1.0/template_django/DjangoHUDApp/templates/pages/page-error.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Error Page{% endblock %}

{% block content %}
	<!-- BEGIN error -->
	<div class="error-page">
		<!-- BEGIN error-page-content -->
		<div class="error-page-content">
			<div class="card mb-5 mx-auto" style="max-width: 320px;">
				<div class="card-body">
					<div class="card">
						<div class="error-code">404</div>
						<div class="card-arrow">
							<div class="card-arrow-top-left"></div>
							<div class="card-arrow-top-right"></div>
							<div class="card-arrow-bottom-left"></div>
							<div class="card-arrow-bottom-right"></div>
						</div>
					</div>
				</div>
				<div class="card-arrow">
					<div class="card-arrow-top-left"></div>
					<div class="card-arrow-top-right"></div>
					<div class="card-arrow-bottom-left"></div>
					<div class="card-arrow-bottom-right"></div>
				</div>
			</div>
			<h1>Oops!</h1> 
			<h3>Η σελίδα αυτή δεν υπάρχει</h3>
			<hr>
			<a href="javascript:window.history.back();" class="btn btn-outline-theme px-3 rounded-pill"><i class="fa fa-arrow-left me-1 ms-n1"></i>Προηγούμενη Σελίδα</a>
		</div>
		<!-- END error-page-content -->
	</div>
	<!-- END error -->
{% endblock %}

hud_django_v1.0/template_django/DjangoHUDApp/templates/pages/page-order.html
{% extends 'base.html' %}

{% load static %}
{% load filters_tags %}

{% block title %}Διακινίσεις{% endblock %}

{% block content %}
    <div class="d-flex align-items-center mb-3">
        <div>
            <h1 class="page-header mb-0">Διακινίσεις</h1>
        </div>
        <div class="ms-auto">
            <a href="add-shipment" class="btn btn-outline-theme"><i class="fa fa-plus-circle fa-fw me-1"></i> Δημιουργία Διακίνησης</a>
        </div>
    </div>
    {% render_shipment_filter_form filter %}

    <div class="card">
        <div class="tab-content p-4">
            <div class="tab-pane fade show active" id="allTab">
                <div class="table-responsive">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th class="border-top-0 pt-0 pb-2"></th>
                                <th class="border-top-0 pt-0 pb-2">Αρ.</th>
                                <th class="border-top-0 pt-0 pb-2">Ημερομηνία</th>
                                <th class="border-top-0 pt-0 pb-2">Παραλήπτης</th>
                                <th class="border-top-0 pt-0 pb-2">Τύπος Αποστολής</th>
                                <th class="border-top-0 pt-0 pb-2">Τρόπος Αποστολής</th>
                                <th class="border-top-0 pt-0 pb-2">Προιόντα</th>
                                <th class="border-top-0 pt-0 pb-2">Σχόλια</th>
                                <th class="border-top-0 pt-0 pb-2">Διαγραφή</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for shipment in shipments %}
                            <tr>
                                <td class="w-10px align-middle">
                                    <a href="{% url 'DjangoHUDApp:order_print' shipment_id=shipment.id %}" class="btn" target="_blank">
                                        <i class="bi bi-printer"></i>
                                    </a>
                                </td>
                                <td class="align-middle">
                                    <a href="{% url 'DjangoHUDApp:pageOrderDetails' shipment.id %}">
                                        #{{ shipment.id }}
                                    </a>
                                </td>
                                <td class="align-middle">{{shipment.date}}</td>
                                <td>{{ shipment.recipient|default:"-" }}</td>
                                <td class="py-1 align-middle">
                                {% if shipment.shipment_type == 'IN' %}
                                    <span class="badge border border-success text-success px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle fs-9px fa-fw me-5px"></i> IN</span>
                                {% elif shipment.shipment_type == 'OUT' %}
                                    <span class="badge border border-warning text-warning px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle fs-9px fa-fw me-5px"></i> OUT</span>
                                {% endif %}
                                    </td>
                                <td class="align-middle"><span class="badge border border-success text-success px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i class="fa fa-circle fs-9px fa-fw me-5px"></i> Fulfilled</span></td>
                                <td class="align-middle">{{ shipment.products_count }}</td>
                                <td class="align-middle">{{shipment.notes}}</td>
                                <td class="align-middle">
                                    <form method="post" action="{% url 'DjangoHUDApp:delete_shipment' shipment.id %}" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
                <div class="d-md-flex align-items-center">
                    <div class="me-md-auto text-md-left text-center mb-2 mb-md-0">
                        Showing {{ shipments.start_index }} to {{ shipments.end_index }} of {{ shipments.paginator.count }} entries
                    </div>
                    <ul class="pagination mb-0 justify-content-center">
                        {% if shipments.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ shipments.previous_page_number }}">Previous</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link">First</a></li>
                        <li class="page-item disabled"><a class="page-link">Previous</a></li>
                        {% endif %}
                        {% for num in shipments.paginator.page_range %}
                        {% if shipments.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% elif num > shipments.number|add:'-3' and num < shipments.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if shipments.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ shipments.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ shipments.paginator.num_pages }}">Last</a></li>
                        {% else %}
                        <li class="page-item disabled"><a class="page-link">Next</a></li>
                        <li class="page-item disabled"><a class="page-link">Last</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="card-arrow">
            <div class="card-arrow-top-left"></div>
            <div the="card-arrow-top-right"></div>
            <div the="card-arrow-bottom-left"></div>
            <div the="card-arrow-bottom-right"></div>
        </div>
    </div>
{% endblock %}

hud_django_v1.0/template_django/DjangoHUDApp/templates/pages/stock-per-warehouse.html
{% extends 'base.html' %}
{% load static %}
{% load filters_tags %}

{% block title %}Products{% endblock %}

{% block content %}
    <div class="d-flex align-items-center mb-3">
        <div>
            <h1 class="page-header mb-0">Αποθέματα / Προιόντα αποθήκης {{ warehouse.name }}</h1>
        </div>
        <div class="ms-auto">
            <a href="{% url 'DjangoHUDApp:add_shipment' %}" class="btn btn-outline-theme"><i class="fa fa-plus-circle fa-fw me-1"></i> Δημιουργία Διακίνησης</a>
        </div>
    </div>

    <!-- Include the filter form -->
    {% render_stock_filter_form filter %}

    <div class="card">
        <div class="tab-content p-4">
            <div class="tab-pane fade show active" id="allTab">
                <!-- BEGIN table -->
                <div class="table-responsive">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th class="pt-0 pb-2"></th>
                                <th class="pt-0 pb-2">Αρ. Μερίδας</th>
                                <th class="pt-0 pb-2">Προιόν</th>
                                <th class="pt-0 pb-2">Απόθεμα</th>
                                <th class="pt-0 pb-2">Κατηγορία</th>
                                <th class="pt-0 pb-2">Χρήση</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for stock_item in stock_items %}
                            <tr>
                                <td class="w-10px align-middle">
                                </td>
                                <td class="align-middle">{{ stock_item.product.batch_number }}</td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <div class="w-50px h-50px bg-inverse bg-opacity-25 d-flex align-items-center justify-content-center">
                                            <!-- Display product image if exists -->
                                            <img alt="{{ stock_item.product.name }}" class="mw-100 mh-100" src="{% if stock_item.product.image %}{{ stock_item.product.image.url }}{% else %}{% static 'img/default-image.jpg' %}{% endif %}">
                                        </div>
                                        <div class="ms-3">
                                            <a href="{% url 'DjangoHUDApp:pageProductDetails' stock_item.product.id %}" class="text-inverse text-opacity-75 text-decoration-none">{{ stock_item.product.name }}</a>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle">{{ stock_item.quantity }}</td>
                                <td class="align-middle">{{ stock_item.product.category.name }}</td>
                                <td class="align-middle">{{ stock_item.product.usage.name }}</td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6" class="text-center">No products found in this warehouse.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- END table -->
            </div>
        </div>
        <div class="card-arrow">
            <div class="card-arrow-top-left"></div>
            <div class="card-arrow-top-right"></div>
            <div class="card-arrow-bottom-left"></div>
            <div class="card-arrow-bottom-right"></div>
        </div>
    </div>
{% endblock %}